/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Collar.glb --transform 
Files: Collar.glb [160.32KB] > C:\Users\dimas\Documents\_MAURICE\maurice-2\public\Collar-transformed.glb [17.05KB] (89%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Collar-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.BézierCurve.geometry} material={nodes.BézierCurve.material} rotation={[0, 0, -Math.PI / 2]} />
    </group>
  )
}

useGLTF.preload('/Collar-transformed.glb')
